# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 19:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Rule content')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_rule', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('reviewed', models.ManyToManyField(related_name='rules', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
