# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_rule', to='employee.Employee', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Rule content'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='reviewed',
            field=models.ManyToManyField(blank=True, related_name='rules', to='employee.Employee', verbose_name='User'),
        ),
    ]
