# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_events', to='employee.Employee', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Event content'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_to', to='employee.Employee', verbose_name='Subscribers'),
        ),
    ]
