# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_company_department_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.Company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
