# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20161208_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_main',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone primary'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_second',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone secondary'),
        ),
    ]
