# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import employee.models.employee


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20161208_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.FileField(default='default.jpg', upload_to=employee.models.employee.avatar_location, verbose_name='User icon'),
        ),
    ]
