# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import employee.models.employee


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20161208_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=employee.models.employee.avatar_location, verbose_name='User icon'),
        ),
    ]
